### ISSUE TITLE
[Improve] - Add prettier to the project

### ISSUE THREAD

**Issue by gurpreet-legend** [gurpreet-legend/Face-Recognition-Braniac-Backend#2]
### Improvements:
- [ ] Add `prettier` to this project to make the code formatting easy fro other developers
- [ ] Add relevant scripts to `package.json` for easy access to prettier commands

Here are steps to add prettier to Node projects, you can refer this article:
https://blog.bitsrc.io/add-prettier-to-your-project-d7e91ac03d05

> ***Note:*** Make sure to format all the files as well using prettier

**Comment by jeroenekkelkamp** [comment]
Can i work on this one? :)

**Comment by gurpreet-legend** [comment]
@jeroenekkelkamp sure, go ahead!

**Comment by jeroenekkelkamp** [comment]
All done!
