### ISSUE TITLE
[Improve] - Add eslint to this project

### ISSUE THREAD

**Issue by gurpreet-legend** [gurpreet-legend/Face-Recognition-Braniac-Backend#3]
### Improvements:
- [ ] Add `eslint` to this project to make the code more robust and readable
- [ ] Add linting scripts to `package.json` for easy access to lint commands

Here are steps to add eslint to Node projects, you can refer this article:
https://dev.to/drsimplegraffiti/eslint-configuration-for-node-project-275l

> ***Note:*** Make sure to lint check all the files as well

**Comment by ThanushaMandala** [comment]
hi @gurpreet-legend can u pls assign this task to me, would like to work on it

**Comment by gurpreet-legend** [comment]
@ThanushaMandala sure, go ahead!

**Comment by ThanushaMandala** [comment]
hi @gurpreet-legend have raised a PR to fix this issue, kindly verify and merge it! Thank you
